### ISSUE TITLE
NoteCards File Browser alters input when recomputing new pattern

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1876] opened 2024-11-03 13:14 UTC
**Describe the bug**

In the NoteCards File Browser, when I recompute to connect to the new pattern `{DSK}<home>paolo>il>webcard>*.notefile;*`, the browser accepts and displays a pattern that differs from the input by 2 missing characters and a capitalized extension, i.e. `{DSK}<home>paolo>il>webcard.NOTEFILE;*` is shown.

This results in no matching files to be found even if present and I have to edit the pattern again to fix it.

**To Reproduce**

1. on Linux, make sure the directory `~/il/webcard/` exists
2. launch Medley
3. click `NOTECARDS`
4. with the File Browser, execute the `Recompute` > `New Pattern` menu command
5. edit the suggested pattern to look like `{DSK}<home>paolo>il>webcard>*.notefile;*`, i.e. delete `notefiles` and type `webcard`

**Expected behavior**

The File Browser connects to the pattern `{DSK}<home>paolo>il>webcard>*.notefile;*`.

**Screenshots**

The default NoteCards File Browser pattern:

![fb-recompute1](https://github.com/user-attachments/assets/21ec4c8c-813b-4c5f-9178-f2deeb6e367a)

The pattern after `Recompute` > `New Pattern`:

![fb-recompute2](https://github.com/user-attachments/assets/844f57fa-9acd-4411-8903-b57f5299f4b6)

The pattern after editing:

![fb-recompute3](https://github.com/user-attachments/assets/0f080fdc-b02c-4431-bf6e-f465846603c3)

The resulting pattern:

![fb-recompute4](https://github.com/user-attachments/assets/69e53b29-c6d9-441b-8c08-0f49dc340138)

**Context (please complete the following information):**

 - OS: Linux Mint Cinnamon
 - OS Version: 22
 - Host arch: x86_64 (System76 Merkaat)
 - Maiko version: N/A
 - IL:MAKESYSDATE: 27-Oct-2024 11:48:39

**Additional context**

The issue occurs only with the NoteCards File Browser and the `webcard` directory.

**Comment by fghalasz** [comment] 2024-11-25 07:07
Fixed in PR#12 in Notecards repo.

Problem was caused by TTYIN (used to collect the New Pattern) truncating the entered response when a CR was issued with the caret in the middle of the line rather than at the end of the line.    Fixed by forcing CR to be the same as CTRL-X when TTYIN is used under NC.AskUser.

**Closed by fghalasz** 2024-11-25 07:07 UTC

**Comment by rmkaplan** [comment] 2024-11-25 17:55
Tedit had a similar issue when it was using TTYINPROMPTFORWORD to get typed-in parameters (e.g. filenames).  About a year ago I fixed at least TTYINPROMPTFORWORD so that it wouldn’t truncate after a CR.  Not sure if that’s relevant to Notecards usage, but…

Issue #1560
