### ISSUE TITLE
XCCS, UTF8, and external formats

### ISSUE THREAD

**Issue by rmkaplan** [Interlisp/medley#313] opened 2021-04-26 06:01 UTC
The next step after EOL conversion will be to convert source files and eventually all files to UTF8/UNICODE.

The EXTERNALFORMAT machinery exists to make this happen on a per-file basis, and we talked about adding another characteristic (:FORMAT ?) to the file-info-expression to say record the external format when the file is made and to restore that external format when the file is read.  For backward compatibility, we would assume XCCS if that characteristic isn't present.  (We will assume that a single attribute (e.g. :UTF8) will imply both transport encoding and character encoding.

In principle, this should be straightforward for Lisp files, just a little fiddling with the define-file-info stuff, since we already have various EXTERNALFORMATs defined.

But the implementation currently is heavily biased for XCCS.  The stream has a single bit that says whether or not it is an XCCS file, in which case it calls in-line macros for character reading/writing. Otherwise, it has accessfns for the various input functions (INCCODE etc) that search for the EXTERNALFORMAT on the stream's property list and extract and apply the relevant function.  

It seems like a first good preparation move is to extend the stream datatype with top-level fields for the  functions, and to copy those functions up out of the externalformat when that is installed into the stream. The external format can stay on the property list, but its content will be lifted up.

It would then be a separate question whether eventually we want to change it so that UTF8/UNICODE are the inline functions.

**Comment by nbriggs** [comment] 2021-04-26 14:58
Any changes to the stream datatype need to be coordinated with the maiko code, which has corresponding C definitions for the stream.  It directly implements the BIN opcode.

**Comment by rmkaplan** [comment] 2021-04-26 15:55
If new fields are added at the end, would coordination still be required?

**Comment by nbriggs** [comment] 2021-04-26 16:07
Not sure.  I haven't read all the stream-aware code (and won't be able to until next week).  You could try it, but if it crashes in weird ways that could be the cause.

**Comment by masinter** [comment] 2021-04-26 22:54
if you're doing Unicode normalization on any path of the XCCS <-> Unicode translations, then GETFILEPTR isn't stable.
I think there might be some cases where file-maps get messed up. Maybe filemaps aren't as important any more, but we still need to insure it's robus.

**Comment by rmkaplan** [comment] 2021-04-26 23:43
I don’t think that’s an issue.  The filemaps are in bytes. (XCCS also reads multiple bytes per character.)

The actual problem is that the closed calls to the character reading functions return 2 values when they are told to report how many bytes they read (as in PFCOPYBYTES), and that’s our prototypical example of stack smashing (XCCS is in-lined).

But I have another question:  How do I edit the STREAM record declaration?  I want to add some pointer fields to the end.

I load SYSEDIT, LOADFROM(FILEIO), EDITREC(STREAM).  Make the changes (just adding a pointer field), and I always get an illegal record declaration error.

Suggestions?

**Comment by masinter** [comment] 2021-04-27 02:39
I can work on the stack-overflow bug but I've never been clear about how to reproduce it. PFCOPYBIYES from where to where with what parameters?
I'm not sure you need to change the STREAM record; I remember something about four extra PTR slots that were there for extensibility (without having to recompile)? Maybe you could sketch out what change you needed to implement this?

**Comment by masinter** [comment] 2021-04-27 02:52
and also while I'm asking,should I raise an issue about EDITREC(STREAM) (which is ED(STREAM RECORDS) ?) 
There should be a WARNING in the STREAM DATATYPE record that the changes need to be coordinated with Maiko and where.

Our goal is to get the code so that it is maintainable by others.

**Comment by rmkaplan** [comment] 2021-04-27 03:57
There is a comment at the top of FILEIO that says that STREAM has to have a fixed datatype number for MAIKO, that it has to be the first DATATYPE in the LOADUP.

But unless MAIKO actually depends on fields that are new and it doesn’t know about, then it ought to be possible to extend it.  Or to put it another way, suppose we did want to make an incompatible change and we were going to coordinate that with Maiko.  It still seems, from my experience, that we can’t use Medley to edit that record.  Maybe there is some special test somewhere for STREAM?

**Comment by rmkaplan** [comment] 2021-04-27 03:58
I’ll send you the provoking test case.  Nick investigated and determined that the stack gets completely scrambled, he hasn’t figured out where or how.  Maybe you’ll see something.

**Comment by rmkaplan** [comment] 2021-04-27 05:30
My mistake.  You have to say “No” when it asks whether the datatype should be redeclared, even with SYSEDIT loaded.

I was able add the fields, and Maiko seems fine with it.

**Comment by masinter** [comment] 2021-04-29 04:50
The name of the category for which utf-8, iso-8859-1, utf-16be, and utf-16  are members is known to the IETF and W3C as "character set" or "charset" for short. These are defined by a registry, https://www.iana.org/assignments/character-sets/character-sets.xhtml . Yes, this conflates the set of characters and the way sequences of characters are encoded into a sequence of bytes, a distinction important if you are developing a translator. However "external format" is not a great choice. My practice when writing RFCs has been to call them "charsets" and I'd like to convince everyone to do the same.

**Comment by rmkaplan** [comment] 2021-04-29 15:59
External format is a commonlisp notion that doesn’t distinguish character codings from byte representations, hence the suggestion for :FORMAT.

**Comment by nbriggs** [comment] 2021-04-30 01:19
From maiko's lsptypes.h -- 
```
/************************************************************************/
/*                                                                      */
/*                      T Y P E   N U M B E R S                         */
/*                                                                      */
/*  These are the type numbers "known to the microcode".  This must     */
/*  match the list \BUILT-IN-SYSTEM-TYPES, in LLDATATYPE.  It's the     */
/*  list of types that MUST be known to microcode or emulator, and      */
/*  which can't rely on the luck of what's loaded when for assignment.  */

#define TYPE_ARRAYBLOCK         0       /* Pseudo type # for array blocks */
#define TYPE_SMALLP             1
#define TYPE_FIXP               2
#define TYPE_FLOATP             3
#define TYPE_LITATOM            4
#define TYPE_LISTP              5
#define TYPE_ARRAYP             6
#define TYPE_STRINGP            7       /* old IL strings (obs) */
#define TYPE_STACKP             8
#define TYPE_CHARACTERP         9
#define TYPE_VMEMPAGEP          10
#define TYPE_STREAM             11

#define TYPE_BITMAP             12
#define TYPE_COMPILED_CLOSURE   13
#define TYPE_ONED_ARRAY         14      /* array, string */
#define TYPE_TWOD_ARRAY         15
#define TYPE_GENERAL_ARRAY      16
[...]
```
it goes on up to type code 64.

**Comment by rmkaplan** [comment] 2021-04-30 03:01
Maybe there should be a file that defines these that is used both by Maiko and in the makeinit?

**Comment by nbriggs** [comment] 2021-04-30 03:04
Is it not that file?

**Comment by rmkaplan** [comment] 2021-04-30 03:08
Dunno.  Does the Medley loadup read it?  The comment at the top of FILEIO says that STREAM has to be loaded first, in order to get the right correspondence.  Maybe the comment is wrong?

**Comment by nbriggs** [comment] 2021-04-30 03:09
LLDATATYPE says:
```
(* ;;
"This is the list of datatypes whos type #s must be known to microcode or to C.")
(* ;; "It is used in \SETUP.HUNK.TYPENUMBERS (in LLARRAYELT) to create the list INITIALDTDCONTENTS for INITDATATYPES.")
(* ;;
"Changes to this lit need to be reflected in C and maybe in microcode.")
                          (VARS \BUILT-IN-SYSTEM-TYPES))
```

and
```
(RPAQQ \BUILT-IN-SYSTEM-TYPES
       ((SMALLP)
        (FIXP 2)
        (FLOATP 2)
        (LITATOM)
        (LISTP 4 (0 2))
        (ARRAYP 6 (0))
        (STRINGP 6 (0))
        (STACKP 2 NIL \RECLAIMSTACKP)
        (CHARACTER)
        (VMEMPAGEP 256 NIL RELEASINGVMEMPAGE)
        (STREAM)
        (BITMAP)
        (COMPILED-CLOSURE 4 (0 2))
        (ONED-ARRAY 8 (0))
        (TWOD-ARRAY 10 (0))
        (GENERAL-ARRAY 10 (0 8))
        (BIGNUM)
        (RATIO)
	(COMPLEX)
        (PATHNAME)
	(NEW-ATOM 10 (2 4 6))
        (FILLER22)
	(FILLER23)
        (FILLER24)
	(FILLER25)
        (FILLER26)
	(FILLER27)
        (FILLER28)
	(FILLER29)
        (FILLER30)))
```

**Comment by nbriggs** [comment] 2021-04-30 03:12
One in C, one in Lisp... and they're not *exactly* the same.   Sigh.
The Lisp version predates the Maiko C version because there was a dependency between the Lisp code and the microcode (and there was no single file that was incorporated into the Lisp and microcode source).

**Comment by rmkaplan** [comment] 2021-05-07 04:42
A progress report on this little project, basically aimed at rationalizing the character input/output interfaces so that the current XCCS default is not built in and favored over Unicode or anything else.  I have attached the spec that I have developed and have pretty much implemented.  It all has to do with external formats.

I have one technical problem that I haven't been able to resolve:  The function \SUBREAD has everything inlined and is so big that with even the slight adjustments of the new macros, it won't compile.  Too many LOCALS.  I have to figure out a rework for that.

That raises the question whether all of the complexity needed to avoid a function call in the default case is really a worthwhile optimization.  Is a single extra function call a noticeable cost, given whatever else is going on to read a character or a byte?

What it does now, to read an XCCS (or whatever new default we install) character, is first to look at the stream to see if it has a function that overrides the default, if not it expands the complicated XCCS code inline.  It could just as easily always call the function in the stream and not bother with any of the inline stuff. (That would also mean that less recompiling would have to be done to switch the default.)

Right now I am also seeing some strange behaviors with SEDIT and TEDIT, so there is more debugging to do before I publish this.
[EXTERNALFORMAT.TXT](https://github.com/Interlisp/medley/files/6439013/EXTERNALFORMAT.TXT)

**Comment by masinter** [comment] 2021-05-08 02:19
“premature optimization is the root of all evil”. I think Knuth might have been serious.
In this case, all of the open compilation makes the nametable and stack frames huge.

I assume you’re talking about \NSIN? The multiple value return is a problem.
Fortunately it isn’t needed in most cases.

I still haven’t figured out how there are 64 pvars even or why your expansion would add so many more.

**Comment by rmkaplan** [comment] 2021-05-08 02:54
After quite a bit of investigation, I figured it out.  The problem was the massive open expansion of \CHECKEOLC for handling the case of  the CRLF end-of-line convention after having seen a carriage return.  It had to do another round of expansions (with the default macros equivalent to the core of \NSIN and \NSPEEK) in order to look ahead and possibly back it out.

And it wasn’t even correct, probably wouldn’t have worked for a linefeed coded in a 16bit file.

So the fix was to put the CRLF handler in a separate closed function (\CHECKEOLC.CRLF), and let the open-coded \CHECKEOLC do the simple LF and CR cases.

The main reason for inling the \INCCODE in the default (:XCCS but eventually :UTF8) is to avoid the multiple-value return on every character when it needs to keep track of byte positions (PFCOPYBYTES and COPYCHARS when byte positions are given—I don’t know if there are other common cases).

I still have random issues with SEDIT.  Have you seen behaviors where the null atom ^@ shows up?  That may be a carry-over from the EOL conversion, I don’t remember when it first started happening.

But there are also various other SEDIT breaks that happen from time to time, not with typing but with mouse clicking perhaps with ctrl/meta keys down.  No URAID crashes, just breaks that appear to safely exit with STOP.

**Comment by masinter** [comment] 2021-05-08 04:29
the Interlisp bytecompiler isn't very sophisticated. It only does pretty minimal dead code removal or optimization.
And the more variables bound, the bigger the frames and setup.
It's a "premature optimization" to do work *in byteswapped lisp* deciding when you're in a "special case" and avoiding a CL:FUNCALL
that would do the dispatch.

**Comment by rmkaplan** [comment] 2021-05-08 05:55
If you don’t detect at least one of the special cases, you will have to do a multiple-value return on every call. That seems to be costly.

**Comment by rmkaplan** [comment] 2021-05-08 23:17
I have published my branch with all of the changes for rationalizing the character IO interfaces.  It is named "Cleanup-character-IO-interfaces. XCCS is stil the default, but I believe I have updated the relevant functions and declarations, and recompiled (with FAKE-COMPILE-FILE for anything containing FUNCTIONS) the consumers of the inline macros.  Most of the modified files are LCOMs, and most of the actual changes were in LLREAD, APRINT, and FILEIO.  But also other modifications to get rid of consumers of the older \NSIN.

This is not yet ready to merge, but I hope people will switch to it and use it for a bit to see if anything fails.

**Comment by masinter** [comment] 2021-05-09 16:47
I think the solution in this phase is to remove special case optimizations, and, if it's really a problem, optimize in a way that actually makes a difference.

**Comment by rmkaplan** [comment] 2021-06-22 05:13
I have isolated almost all of the XCCS dependencies through the externalformat machinery.  There is still (at least one, hopefully not many) vestige that I am unsure about.  There is a documented function CHARSET that can be used to get and set the current character set of an NS-runcoded stream, with T indicating a non-runcoded stream (uniformatly 2-byte characters).  CHARSET is also provided as an OPENSTREAM parameter, and sets the character on open (by setting the stream's charset and also writing a few bytes if it is an output file).

It may be reasonable to fetch the character set, if it happens to be a runcoded XCCS file.  But is there ever any purpose in actually setting the character set?  That would only be useful for an application that knew that it was working on an XCCS stream, set it up to be runcoded, knowing that, ran code that bin'd or bout'ed a sequence of low-order bytes from the characters in some sequence.  The more normal usage would be to print 16-bit characters, and let the stream deal with the character-set runs.

It is possible to preserve the logic of this, even if we go to UT8 or some other external format.  We could allow for runcoded non-XCCS streams, meaning that the stream could have a high-order cset byte that it packs on to every byte that it reads and packs on to every byte that it is asked to print. 

We could simulate runcoding and charsets for arbitrary external formats from the Medley programmer's point of view (by packing high order bytes before writing and masking out high order bytes on reading (presumably by recording the last charset so we can simulate runcoding), but presumably also the file itself would just have its proper encoding of characters.

Is it worth trying fake up this kind of behavior?

**Comment by nbriggs** [comment] 2021-06-22 16:00
CHARSET is used by the lispusers package READINTERPRESS (btw, so is \NSIN)

-- Nick

**Comment by nbriggs** [comment] 2021-06-22 16:05
I also notice that LAFITE uses \NSIN because
	"Eat chars til eol.  Optimize here with \NSIN because this operation wants to be fast, while READCCODE is slow."

**Comment by rmkaplan** [comment] 2021-06-22 17:02
Thanks.  I’ll look at those.  The difference now, in the NS case, is two function calls (the \INCCODE before it dispatches and then the now-closed call to the XCCS external format function).  The \INCCODE wrapper is trivial and could be macroed out eventually.  But these interface function calls are all in the noise compared to the other stream dispatches and testing.

(And thinking about Lafite and Mime, it might be helpful to add a BASE64 external format)

**Comment by rmkaplan** [comment] 2021-06-22 17:59
Lafite also is fiddling around with the NS charset in some way, something to do with EOF.  I don’t understand it, but it should still work on an NS stream.  I'll save it for later.

**Comment by rmkaplan** [comment] 2021-06-22 19:27
More on Lafite:  It is setting up an end-of-stream operation to return EOL's instead of erroring every time it is called at the end of the file, with the idea that the number of calls is bounded by its state in some parsing sequence.  The problem is a general one, for endofstreamops:  They are invoked on a byte-read operation, but the caller is presumably invoking a character reading operation (like \INCCODE) that pieces together character codes out of possibly a sequence of bytes. So the lafite EOF function is trying to simulate the runcoded byte sequence that would represent the EOL when the stream is not already in character set 0.  That will let the character-code reading interpret it in the right way.

If not in CSET 0, on a first call it returns the NS shift byte, recording as a stream prop the fact that it had done that.  On the next call it puts out the 0 for cset 0, recording that it had done that, and on the third call it puts out the EOL  (It doesn't deal with the non-runcoded case, where it should just put out a 0 and then the EOL.)

The general problem, though, is that this EOF function, and maybe others, has to simulate a non-existent byte sequence that encodes the EOL character (and perhaps also the EOL convention) so that the character reader next level up can do the right thing.  Easy enough for UTF8 or other encodings where the CR/LF's are single bytes. Not sure about EUC or JIS or other encodings that someone might stick in.  

This is on the fringe of the effort to keep the alignment between byte transport encodings and logical characters.  I'm not sure how to abstract and generalize this one.

**Comment by masinter** [comment] 2021-06-22 22:03
There were different generations of evolution of code from PDP-10 to Interlisp for Vax and Jericho and D-machine and Medley and Common Lisp.   It will be difficult to reliably revamp all of the existing code without unraveling too much.
Consider the possibility of making simplified assumptions:
UTF8 with LF/EOL  and XCCS with CR/EOL are the ONLY external formats in Lisp core,
and that any other external formats might be supported by a transformational stream device.

**Comment by rmkaplan** [comment] 2021-06-22 23:16
One way of addressing this particular issue, and maybe others, is to add another external format function  that is given a controlling stream (the input stream in the Lafite case, but maybe also an output stream for some other purpose) whose current status and properties (charset or whatever) can be inspected, and a temporary io stream (nodircore, or some commonlisp-type stream) that the relevant format properties can be copied on to.  It would return the updated temporary io stream.

Then ordinary printing functions can be applied to print whatever the application wants in the appropriate byte sequence, by virtue of the format's \OUTCHAR function.  The bytes on that stream can be binned back as needed, or perhaps just counted, or perhaps a higher level wrappper would return them in a string for GNC.  

This would be a systematic way of determining, whether for the Lafite application or something else, the printed byte representation of any Lisp object, going through the already defined \OUTCHAR function.  Basically, it just has to transfer the stream properties that the particular format cares about, so that ordinary printing functions can then be applied.

**Comment by masinter** [comment] 2021-08-05 20:41
Can we close this issue when PR #381 is merged?

**Comment by rmkaplan** [comment] 2021-08-06 00:17
Yes.  We may still need to do some fine tuning (like FILEPOS), and there will be a separate attack on TEDIT plaintext files.  But those will be separate issues

**Closed** 2021-08-06 03:04 UTC
