### ISSUE TITLE
[TEdit 14-Jan-2024] TEDIT / LISPSOURCEFILEP breaks on opening a text file containing a single 0xFF character

### ISSUE THREAD

**Issue by nbriggs** [Interlisp/medley#1510] opened 2024-01-17 00:07 UTC
**Describe the bug**

TEDIT / LISPSOURCEFILEP breaks on opening a text file containing a single 0xFF character

**To Reproduce**
1. Create file containing only a 0xFF character (e.g., printf '\377' >/tmp/foo.txt )
2. (TEDIT "{dsk}/tmp/foo.txt")
3. BREAK, END-OF-FILE, in SKIPSEPRCODES

**Expected behavior**

Open the file without an error.

**Context (please complete the following information):**
 - OS: macOS
 - OS Version: BigSur
 - Host arch: x86_64
 - Maiko version: b666b1b [git rev-parse --short HEAD]
 - IL:MAKESYSDATE: "15-Jan-2024 10:16:14" on branch Tedit-4th-round
 
[btv.txt](https://github.com/Interlisp/medley/files/13956934/btv.txt)

**Comment by rmkaplan** [comment] 2024-01-17 02:39
Looks like the problem is at a lower level, SKIPSEPRCODES or probably the XCCS INCCCODEFN.  A related issue was discussed in the meeting yesterday, before you arrived.  Larry ran a GREP on a TEDIT binary file, and that had 255 sequences that are illegal in XCCS.  The question is, what to do?  Cause an error?  Return a particular character code that from a region of codespace that is undefined for both Unicode and XCCS?  UTF-8 will have the same problem, if applied to a binary file--some (binary) byte sequences are invalid character encodings.

**Comment by rmkaplan** [comment] 2024-01-17 03:45
(BTW, Larry's GREP was the lispusers GREP package that uses FILEPOS on characters decoded from their external format)

**Comment by rmkaplan** [comment] 2024-01-17 18:01
A simpler example:  Create file X with a single 255 byte, do (READCCODE X), get an EOF error.

What should it do?  Return 255, or something else?

**Comment by nbriggs** [comment] 2024-01-17 19:28
How was X opened -- if it was
```
(SETQ X (OPENSTREAM "filename.here" 'INPUT 'OLD '((TYPE BINARY))))
```
 then I'd rather expect it to return 255, as if it were reading bytes [though it doesn't]

But, the documentation for (LISPSOURCEFILEP _FILE_) says: "Returns a non-NIL value if _FILE_ is an Interlisp source file, NIL otherwise", so I wouldn't expect it to fail with an end-of-file error.

**Comment by rmkaplan** [comment] 2024-01-17 19:38
If you want to treat it really as a binary (= byte) file, then your shouldn’t be doing character-level operations (READCCODE, SKIPSEPRS…, RATOM) and expect any XCCS or UTF-8 interpretation.  Or, maybe type BINARY should imply that the external format is :THROUGH (a name inherited from the ancient past).

**Comment by nbriggs** [comment] 2024-01-17 19:42
But if I, or TEDIT (in this case), don't know what the file is and happen to use LISPSOURCEFILEP on it, it should never break.  In the direct LISPSOURCEFILEP case one may be passing the (string) name of the file, never having opened it.

**Comment by rmkaplan** [comment] 2024-01-17 19:59
So, just have LISPSOURCEFILEP embed everything under an NLSETQ, return NIL if an error happens?

**Comment by nbriggs** [comment] 2024-01-17 20:15
Apparently it's a multiple-value-return, does that play well with an NLSETQ?  But yes, it can just return NIL if it's not a (managed?) lisp source file.

![image](https://github.com/Interlisp/medley/assets/8138841/eba5c622-ca70-4b7f-b6fd-5f7290a1048c)

I think that will get past the call to LISPSOURCEFILEP in TEDIT.  The next thing that will happen (after I advised LISPSOURCEFILEP to return NIL) is that TEDIT will open the file, without error, but says that the file is empty.  Attempting to BIN the TEXTSTREAM of the window gets a "NIL is not a number" error (BIN => \BIN => \TEXTBIN => IDIFFERENCE), but that is the same behavior as a real empty file, or a fresh TEdit window that hasn't yet got anything in it (though a different error from old TEdit, which failed with ARG NOT PIECE/LASTPIECE on a new empty TEdit window).

**Comment by nbriggs** [comment] 2024-01-17 20:50
I looked at LISPSOURCEFILEP, and noticed that the comments say "If the first few characters of FILE `look like' those output by MAKEFILE then return the alleged address in the file of its FILEMAP expression.", while the values returned are (CL:VALUES ENV MAP), where based on the comments I'd expect (CL:VALUES MAP ENV) so multiple-value naive code would get the position of the filemap.   Does anyone rely on this?

**Comment by rmkaplan** [comment] 2024-01-17 21:29
The way this is now hooked into Tedit, the reader environment returned by LISPSOURCEFILEP is used to get the file’s readtable, and the readtable is then used to set up Tedit’s wordbound table so that when you do a word-select in the middle of an atom in the Tedit window it will expand to catch the whole atom.  Same with the “tf” command for an individual function.

Maybe there is a dependency somewhere else.

**Comment by rmkaplan** [comment] 2024-01-18 18:49
Fixed in PR rmk103

**Closed** 2024-01-20 05:53 UTC
Labels: bug
