### ISSUE TITLE
Banner image missing from Interlisp.org home

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1549] opened 2024-02-21 11:29 UTC
The banner image is missing from the home page of [Interlisp.org](https://interlisp.org) which looks like this:

![interlisporg-home](https://github.com/Interlisp/medley/assets/10342479/4f45bad0-3613-4915-8a37-0b3bb42b18d0)

I'm using an ASUS Chromebox 3 with chromeOS Stable 121.0.6167.188 and clearing the cache has no effect. The image is missing also when visiting the site from my Android phone with Chrome.

**Comment by stumbo** [comment] 2024-02-21 14:55
The issue is an upgrade to Hugo - version `0.123.0` was forcing case changes in Resource files.  I believe the regression was fixed in `0.123.1`.  However, I set the version back to `0.122.0` and will further investigate before resetting back to latest.

**Comment by stumbo** [comment] 2024-08-27 03:54
This is resolved.  We've are currently running Hugo version 0.127 with no issues with resources.

**Closed by stumbo** 2024-08-27 03:54 UTC
