### ISSUE TITLE
BACKGROUNDIMAGES Shade editor seems to hang the entire system

### ISSUE THREAD

**Issue by sethm** [Interlisp/medley#173] opened 2021-02-06 16:23 UTC
**Describe the bug**

After loading the BACKGROUNDIMAGES Lisp User's Module, attempting to edit the appearance of the default background shade seems to hang the system. It no longer accepts mouse or keyboard input.

**To Reproduce**

1. Run `./run-medley -full`
2. Open a new Interlisp Exec
3. Run `(FILESLOAD 'PRESS 'BACKGROUNDIMAGES)`
4. Run `(BACKGROUND.SETUP)`
5. From the Background Menu, select "Background -> Shade"
6. Attempt to edit the background shade bitmap

After the first mouse click in the main editing area, no more user input is accepted into the system.

**Expected behavior**

Expected that the background shade bitmap should be editable.

**Context (please complete the following information):**
 - OS: Linux
 - OS Version: Linux Mint 20.1
 - Host arch: x86_64
 - Maiko git commit: 9957f5c305c85141cc3a5f874c7418218133fc58
 - Medley git commit: dfb28cec43f3d1c7a3a3dc19f4a43f3d212f766a
 - IL:MAKESYSDATE: 1-Feb-2021 22:38:08

**Comment by nbriggs** [comment] 2021-02-09 06:54
It's easy to reproduce, without loading any additional packages, call `(EDITSHADE)` and then try to add bits to the shade bitmap.

**Comment by nbriggs** [comment] 2021-02-09 21:51
The immediate issue is that `getXsignaldata()` is not being called when necessary -- the fd for the display connection is not showing "ready" in the `select()`, so we don't call it.  Removing that check solves this problem.  I'd like to understand where things are hanging up, though, because it looks as though it may end up blocking (or looping waiting for an event) in the X library.

**Comment by sethm** [comment] 2021-02-10 02:08
I just made a discovery that I hope may help track down what's going on. I checked out the `experiment-yield-subr` branch of maiko, built it, and then did the following:

1. I confirmed that the bug could be reproduced by running `(EDITSHADE)` on a fresh Medley checkout, and it can be.
2. Then, I restarted Medley and followed the [instructions on the Wiki](https://github.com/Interlisp/medley/wiki/How-to-Run-Medley-without-pinning-the-CPU) about setting the `BACKGROUND-YIELD` function.
3. After adding `BACKGROUND-YIELD` to `BACKGROUNDFNS`, the bug appears to be gone. I can run `(EDITSHADE)` and it's fully responsive.

I don't know enough about Maiko or Medley to understand the interaction here, but I hope it's a useful clue.

**Comment by nbriggs** [comment] 2021-02-10 02:18
Thanks for the update.  Yes, that will relieve the proximal cause of the problem because the code I put in the background yield will force the system through a check for I/O (going through `getXsignaldata()` in maiko).  I'm still tracking down exactly how we got to that point though -- the EDITSHADE code notices a mouse-button-down event, and then loops waiting for a mouse-button-up state, and that should not freeze out processing of X events, but that might not really be the root cause, so I'm still looking...

**Comment by masinter** [comment] 2021-03-04 00:41
Is this the same problem with cygwin? There are no X interrupts? but you don't want to poll for data without an assurance that won't hang?

**Comment by masinter** [comment] 2021-09-03 07:02
Fixed by https://github.com/Interlisp/maiko/pull/392

**Closed** 2021-09-03 07:05 UTC
Labels: bug, maiko
