### ISSUE TITLE
Syntactically complete Common Lisp expression not evaluated

### ISSUE THREAD

**Issue by pamoroso** [Interlisp/medley#1535] opened 2024-02-11 12:48 UTC
I've come across a really weird issue.

When I enter at a XCL Exec a specific, syntactically complete Common Lisp expression that contains a macro call, nothing happens after typing the matching closing paranthesis that completes the expression.

To reproduce, load into Medley slightly modified versions of the [source files](https://gigamonkeys.com/book/practicals-1.0.3.zip) of the simple database example in [Chapter 3](https://gigamonkeys.com/book/practical-a-simple-database) of Peter Seibel's book *Practical Common Lisp*. For your convenience I've attached the modified files (renamed from `.lisp` to `.txt` so that GitHub can upload them):

* [packages.txt](https://github.com/Interlisp/medley/files/14232409/packages.txt)
* [simple-database.txt](https://github.com/Interlisp/medley/files/14232411/simple-database.txt)

I modified the file `packages.lisp` by adding the comment `;;; packages.lisp` at the beginning and substituting `:xcl-user` for `cl-user` in `in-package`. And I added to the file `simple-database.lisp` the comment `;;; simple-database.lisp`.

First off, at an XCL Exec in Medley load both files:

1. `(load "packages.lisp")`
1. `(load "simple-database.lisp")`

Next, for convenience evaluate:

```lisp
> (setf *package* (find-package "COM.GIGAMONKEYS.SIMPLE-DB"))
```

Finally, evaluate:

```
> (where :artist "not found")
```

After typing the closing parenthesis nothing happens. No text can be typed, no return value is printed, and the prompt doesn't reappear. Instead I'd expect the expression to return a function like in SBCL:

```
* (where :artist "not found")
#<FUNCTION (LAMBDA (CD)) {54A8ADEB}>
```

The expression looks like this in Medley after typing the closing parenthesis:

![cl-macro-call](https://github.com/Interlisp/medley/assets/10342479/8a9e4293-fced-482f-9b1e-ecb89c1d7d41)

To get back control of the Exec I have to press `Ctrl-E` or `Ctrl-D`. If I press `Ctrl-B` I get this break window whose backtrace might hold clues:

![cl-macro-call-break](https://github.com/Interlisp/medley/assets/10342479/86097618-aaa3-4b92-9a16-b4794b9819e9)

I use Medley Online 15-Sep-2023 23:14:52 on chromeOS 121.0.6167.159.

**Comment by tfeb** [comment] 2024-02-11 13:55
(Wild guess): what's the value of *print-circle*?On 11 Feb 2024, at 12:49, Paolo Amoroso ***@***.***> wrote:﻿
I've come across a really weird issue.
When I enter at a XCL Exec a specific, syntactically complete Common Lisp expression that contains a macro call, nothing happens after typing the matching closing paranthesis that completes the expression.
To reproduce, load into Medley slightly modified versions of the source files of the simple database example in Chapter 3 of Peter Seibel's book Practical Common Lisp. For your convenience I've attached the modified files (renamed from .lisp to .txt so that GitHub can upload them):

packages.txt
simple-database.txt

I modified the file packages.lisp by adding the comment ;;; packages.lisp at the beginning and substituting :xcl-user for cl-user in in-package. And I added to the file simple-database.lisp the comment ;;; simple-database.lisp.
First off, at an XCL Exec in Medley load both files:

(load "packages.lisp")
(load "simple-database.lisp")

Next, for convenience evaluate:
> (setf *package* (find-package "COM.GIGAMONKEYS.SIMPLE-DB"))
Finally, evaluate:
> (where :artist "not found")

After typing the closing parenthesis nothing happens. No text can be typed, no return value is printed, and the prompt doesn't reappear. Instead I'd expect the expression to return a function like in SBCL:
* (where :artist "not found")
#<FUNCTION (LAMBDA (CD)) {54A8ADEB}>

The expression looks like this in Medley after typing the closing parenthesis:
cl-macro-call.png (view on web)
To get back control of the Exec I have to press Ctrl-E or Ctrl-D. If I press Ctrl-B I get this break window whose backtrace might hold clues:
cl-macro-call-break.png (view on web)
I use Medley Online 15-Sep-2023 23:14:52 on chromeOS 121.0.6167.159.

**Comment by pamoroso** [comment] 2024-02-11 14:03
The value of `*print-circle*` is `nil` as in this session:

![print-circle](https://github.com/Interlisp/medley/assets/10342479/870e1b4d-87ad-4c7c-b1c5-6a9bfaa171a2)

Setting `*print-circle*` to `t` yelds the same outcome.

**Comment by nbriggs** [comment] 2024-02-11 17:12
It's going into an infinite loop trying to expand the `where` macro.  A likely culprit could be the lack of a proper `loop` implementation, interfering with `make-comparison-list`...?

**Comment by pamoroso** [comment] 2024-02-11 17:25
You're right, I hadn't noticed the code uses `loop`.

**Comment by pamoroso** [comment] 2024-02-11 17:30
We discussed the incomplete implementation of `loop` in #1473.

**Comment by nbriggs** [comment] 2024-02-11 17:30
`(loop while fields collecting ...)` is probably equivalent to Interlisp's `(il:while fields il:collect ...)` -- so you could just rewrite that function and see if you get expected results.

**Closed** 2024-02-12 11:21 UTC
